### ISSUE TITLE
Open 3D files?

### ISSUE THREAD

**Issue by MarcelRobitaille** [zapta/legacy_stepper_motor_analyzer#10]
The 3D folder only has `.stl` files. Would it be possible to have them as a step or similar?

**Comment by zapta** [comment]
These are the two onshape projects. Can you see them? Can you export in the
format of your choice?

https://cad.onshape.com/documents/146b8b994145177887407b23/v/0a1e5f034a5403b7d545e8f5/e/b6453eca2ba530476c30538a

https://cad.onshape.com/documents/c2cb2c3a5f0213b18ca23aa6/v/0c557975f7362fe0b01ac51c/e/1478128b17ff3afd79bedf8b

**Comment by MarcelRobitaille** [comment]
That is better than a step. I use OnShape too. Thank you so much.
